### ISSUE TITLE
Build issues on Windows environments

### ISSUE THREAD

**Issue by gordongrace** [govau/uikit-starter#12]
Error generated on fresh Windows 10 environment after NodeJS install and running through build instructions for uikit-starter:

```
C:\Users\USER\Documents\Code\uikit-starter\node_modules\uws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\USER\Documents\Code\uikit-starter\node_modules\uws
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

Running `npm install sass` manually before re-running `npm install` for `ui-kit-starter` appeared to solve the issue

**Comment by alex-page** [comment]
Hi @gordongrace thanks for the detailed issue.

I currently don't have a windows device however I'm happy to look into this in more detail tomorrow.

I did a google search around the error you received.
```
Error: Can't find Python executable "python"
```

It sounds like there is a problem with Windows 10 connecting to python with NPM. Maybe you can have a look at this issue for windows build tools: https://github.com/felixrieseberg/windows-build-tools/issues/56#issuecomment-308739624

Another solution may be removing your `node_modules` folder and running `npm install` again.

**Comment by alex-page** [comment]
I just installed the `uikit-starter` on windows without any issues. Potentially the download for `node-sass` failed which is why reinstalling it fixed your problem.

If you notice the problem again please let me know happy to re open the issue.
