### ISSUE TITLE
no more update?

### ISSUE THREAD

**Issue by iijiang** [govau/uikit-starter#3]
from the docs says npm install? install what? is this a no more update?

**Comment by alex-page** [comment]
@iijiang The documentation of the starter kit is going to updated soon. I understand it's not in the best state. I'll try and outline my process here to help you.

If you are using a windows computer there is a pull request which should fix up some issues as well.

1. `git clone https://github.com/govau/uikit-starter.git`
2. `cd uikit-starter`
3. `npm install`
4. [If you are using Windows, update your package.json ](https://github.com/govau/uikit-starter/pull/1/commits/9c2740f8e94a607aebedadf9fc2e7612a995f3ef)
5. `npm run watch`
