### ISSUE TITLE
css not loaded due to mime type strict enforcing + css classes

### ISSUE THREAD

**Issue by veenarm** [govau/uikit-starter#8]
Chrome among others fails to import the css as no type is defined.
<link rel="stylesheet" href="css/main.css"> should have  type="text/css" included.

Otherwise it comes up with 
https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type

Could of done a pull, but not worth it - I'll be playing with this soon enough :)

- Actually the whole index.html looks like it needs updating as it still referrences uikit- CSS classes, when the UI2KIT is now au-  (correct me if I'm wrong)..

**Comment by alex-page** [comment]
Hi @veenarm thanks for finding this.

I updated the starterkit in this PR https://github.com/govau/uikit-starter/pull/9 after review it should fix your issue.
